version: 3.0.{build}
image: Visual Studio 2019
platform:
- Win32
- x64
configuration:
- Release
install:
- git submodule update --init --recursive
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.dll'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.pdb'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true